name: android-multi-ABIs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the CMake build directory.
  build: "${{ github.workspace }}/build"
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - preset: android-arm-clang-shared
          # - preset: android-arm64-clang-shared
          # - preset: android-x86-clang-shared
          # - preset: android-x86_64-clang-shared

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build pkg-config cmake
      
    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg integrate install

    - name: Set Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        add-to-path: false
      run: ./build.sh
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Confihure Cmake
      run: cmake -S . -B ${{ env.build }} --preset ${{matrix.config.preset}}
    - name: Build CMake in Debug mode
      run: cmake --build ${{ env.build }} --config Debug

    - name: Build CMake in Release mode
      run: cmake --build ${{ env.build }} --config Release
        
